services:
  - type: web
    name: arvi-stripe-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: "npm install"
    startCommand: "node --import ./03infrastructure/telemetry/telemetry.js server.js"
    autoDeploy: true

    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false

      - key: STRIPE_WEBHOOK_SECRET
        sync: false

      - key: OTEL_SERVICE_NAME
        value: "arvi-backend"

      - key: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "https://otlp-gateway-prod-eu-central-0.grafana.net/otlp"

      - key: OTEL_EXPORTER_OTLP_HEADERS
        sync: false

      - key: SUCCESS_BASE_URL
        value: "https://getarvi.com/success"

      - key: CANCEL_URL
        value: "https://getarvi.com/cancel"
