services:
  - type: web
    name: arvi-stripe-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false        # la pondrá a mano en Render
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
