/**
 * Layer: Application
 * File: HabitSeriesFromAIMapper.js
 * Responsibility:
 * Maps validated AI output into a HabitSeries domain entity, coupling AI output structure to domain construction.
 */

import { HabitSeries } from "../../01domain/entities/HabitSeries.js";
import { Action } from "../../01domain/value_objects/habits/Action.js";

/**
 * Maps parsed AI output into a HabitSeries domain entity.
 *
 * @param id - Series ID (generated by persistence layer)
 * @param aiOutput - Validated AI output with title, description, and actions
 * @returns A valid HabitSeries domain entity
 */
function mapAIOutputToHabitSeries(
  id,
  aiOutput
) {
  console.log(`[MAPPER] [Application] mapAIOutputToHabitSeries called for id=${id}, actions=${aiOutput.actions.length}`);

  const actions = aiOutput.actions.map((raw, index) =>
    Action.fromAIOutput(raw, `${id}_action_${index}`)
  );

  const habitSeries = HabitSeries.create({
    id,
    title: aiOutput.title,
    description: aiOutput.description,
    actions,
  });

  console.log(`[MAPPER] [Application] mapAIOutputToHabitSeries OK → title="${habitSeries.title}", actions=${habitSeries.actions.length}`);

  return habitSeries;
}

export { mapAIOutputToHabitSeries };
