/**
 * HabitSeriesFromAIMapper (Application Layer)
 *
 * Transforms parsed AI output into a valid HabitSeries domain entity.
 *
 * This is the ONLY place where AI output structure is coupled
 * to domain entity construction. The domain itself remains
 * fully agnostic of AI concerns.
 */

import { HabitSeries } from "../../01domain/entities/HabitSeries.ts";
import { Action } from "../../01domain/value_objects/habit_objects/Action.ts";

/**
 * Maps parsed AI output into a HabitSeries domain entity.
 *
 * @param id - Series ID (generated by persistence layer)
 * @param aiOutput - Validated AI output with title, description, and actions
 * @returns A valid HabitSeries domain entity
 */
export function mapAIOutputToHabitSeries(
  id: string,
  aiOutput: {
    title: string;
    description: string;
    actions: readonly { name: string; description: string; difficulty: string }[];
  }
): HabitSeries {
  const actions = aiOutput.actions.map((raw, index) =>
    Action.fromAIOutput(raw, `${id}_action_${index}`)
  );

  return HabitSeries.create({
    id,
    title: aiOutput.title,
    description: aiOutput.description,
    actions,
  });
}
